name: Build And Release

on:
  push:
    branches:
      - main
      - stage

jobs:
  build_then_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
