name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - stage
  push:
    branches:
      - stage

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Dependencies
        run: yarn install

      - name: Run Semantic Release
        if: github.event.pull_request.merged == true || github.ref == 'refs/heads/stage'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
